Repository 0oWoodenDooro0/LevelDevil, pull requests merged in 2024-04, with the labels that each got.

#45 第一關關卡物件
  Resources/image/level/level1/background.png
  Resources/image/level/level1/bottom.png
  Resources/image/level/level1/move1.png
  Resources/image/level/level1/move2.png
  Resources/image/level/level1/side.png
  Resources/image/level/level1/top.png
  files.cmake
  include/App.hpp
  include/Button.hpp
  include/Character.hpp
  include/Coin.hpp
  include/Door.hpp
  include/DoorButton.hpp
  include/EscButton.hpp
  include/InputHandler.hpp
  include/Level1.hpp
  include/LevelSelect.hpp
  include/MovableSprite.hpp
  include/Spike.hpp
  include/Spring.hpp
  include/Sprite.hpp
  include/TriggerCollider.hpp
  src/App.cpp
  src/Button.cpp
  src/Character.cpp
  src/Coin.cpp
  src/Door.cpp
  src/DoorButton.cpp
  src/EscButton.cpp
  src/InputHandler.cpp
  src/Level1.cpp
  src/LevelSelect.cpp
  src/MovableSprite.cpp
  src/Rigidbody.cpp
  src/Spike.cpp
  src/Spring.cpp
  src/Sprite.cpp
Labels: enhancement

#50 rename StageClear to CloseDoor
  include/Door.hpp
  src/Door.cpp
Labels: enhancement

#53 fix escbutton not work
  src/Button.cpp
  src/Level1.cpp
Labels: bug

#55 fix checkpoint
  src/Character.cpp
Labels: bug

#52 Level2 init
  README.md
  Resources/image/background/test_background.png
  Resources/image/component/LbuttonDown.png
  Resources/image/component/LbuttonUp.png
  Resources/image/level/level1/door.png
  Resources/image/level/level1/in_door1.png
  Resources/image/level/level1/in_door3.png
  Resources/image/level/level1/in_door4.png
  Resources/image/level/level1/in_door5.png
  Resources/image/level/level2/Lbottom.png
  Resources/image/level/level2/Lside.png
  Resources/image/level/level2/Ltop.png
  Resources/image/level/level2/Rbottom.png
  Resources/image/level/level2/Rtop.png
  Resources/image/level/level2/background.png
  Resources/image/level/level2/door.png
  Resources/image/level/level2/hole.png
  Resources/image/level/level2/in_door1.png
  Resources/image/level/level2/in_door2.png
  Resources/image/level/level2/in_door3.png
  Resources/image/level/level2/in_door4.png
  Resources/image/level/level2/in_door5.png
  Resources/image/level/level2/level2.aseprite
  Resources/image/level/level2/spike.png
  files.cmake
  include/Door.hpp
  include/Level.hpp
  include/Level2.hpp
  include/LevelButton.hpp
  src/Door.cpp
  src/Level2.cpp
  src/LevelButton.cpp
Labels: enhancement

#56 fix image line when position is float
  include/Level1.hpp
  src/Level1.cpp
  src/MovableSprite.cpp
Labels: bug

#57 sy
  src/App.cpp
  src/Level2.cpp
  src/LevelButton.cpp
  src/LevelSelect.cpp
Labels: enhancement

#60 fix revive to KeycodeDown
  include/InputHandler.hpp
  src/InputHandler.cpp
  src/Level1.cpp
Labels: bug

#65 deltaTime to deltaTimeMs
  include/AudioManager.hpp
  include/Door.hpp
  include/Spring.hpp
  src/Character.cpp
  src/Door.cpp
  src/MovableSprite.cpp
  src/SoundEffect.cpp
  src/Spring.cpp
Labels: refactor

#68 intro outro easeIn easeOut
  files.cmake
  include/Button.hpp
  include/EasingFunction.hpp
  include/Level1.hpp
  include/Level2.hpp
  include/LevelSelect.hpp
  include/Transition.hpp
  src/Level1.cpp
  src/Level2.cpp
  src/LevelSelect.cpp
  src/Transition.cpp
Labels: enhancement

#72 code-smells
  include/Animator.hpp
  include/Collider.hpp
  include/Door.hpp
  include/ILevel.hpp
  include/Level1.hpp
  include/Level2.hpp
  include/LevelButton.hpp
  include/LevelSelect.hpp
  include/SoundEffect.hpp
  include/Spring.hpp
  src/Animator.cpp
  src/App.cpp
  src/Collider.cpp
  src/Door.cpp
  src/Level1.cpp
  src/Level2.cpp
  src/LevelButton.cpp
  src/LevelSelect.cpp
  src/SoundEffect.cpp
  src/Spring.cpp
Labels: refactor

#77 Coin update
  include/Coin.hpp
  src/Coin.cpp
Labels: enhancement

#78 root>renderer
  Resources/image/level/level4/background.png
  Resources/image/level/level4/bottom.png
  Resources/image/level/level4/door.png
  Resources/image/level/level4/in_door1.png
  Resources/image/level/level4/in_door2.png
  Resources/image/level/level4/in_door3.png
  Resources/image/level/level4/in_door4.png
  Resources/image/level/level4/in_door5.png
  include/Level.hpp
  include/Level1.hpp
  include/Level2.hpp
  src/Level1.cpp
  src/Level2.cpp
Labels: enhancement

#82 Rigidbody fix
  include/Character.hpp
  include/CollisionHandler.hpp
  include/Rigidbody.hpp
  include/Sprite.hpp
  src/Character.cpp
  src/CollisionHandler.cpp
  src/Rigidbody.cpp
Labels: enhancement, refactor
