Repository 0oWoodenDooro0/LevelDevil, pull requests merged in 2024-03, with the labels that each got.

#1 change readme
  README.md
Labels: enhancement

#9 Rigidbody
  files.cmake
  include/Character.hpp
  include/Rigidbody.hpp
  src/Character.cpp
  src/Rigidbody.cpp
Labels: enhancement

#15 fix-collider-bug
  include/Character.hpp
  src/App.cpp
  src/Rigidbody.cpp
Labels: bug

#16 add character sfx
  Resources/sound/jump.mp3
  Resources/sound/run.mp3
  files.cmake
  include/App.hpp
  include/AudioManager.hpp
  include/Character.hpp
  include/SoundEffect.hpp
  src/App.cpp
  src/AudioManager.cpp
  src/Character.cpp
  src/SoundEffect.cpp
Labels: enhancement

#14 door
  Resources/image/button/escbtn_down.png
  Resources/image/button/escbtn_up.png
  Resources/image/door/door.png
  Resources/image/door/in_door1.png
  Resources/image/door/in_door2.png
  Resources/image/door/in_door3.png
  Resources/image/door/in_door4.png
  Resources/image/door/in_door5.png
  files.cmake
  include/App.hpp
  include/Character.hpp
  include/Door.hpp
  src/App.cpp
  src/Character.cpp
  src/Door.cpp
  src/Spike.cpp
Labels: enhancement

#21 Button
  files.cmake
  include/Button.hpp
  include/CollisionHandler.hpp
  src/Button.cpp
  src/CollisionHandler.cpp
Labels: enhancement

#24 修改Button
  include/Button.hpp
  src/Button.cpp
Labels: enhancement

#31 新增 set level
  include/App.hpp
  src/App.cpp
Labels: enhancement

#32 新增 behaviour enable disable
  files.cmake
  include/Behaviour.hpp
  include/Button.hpp
  include/Character.hpp
  include/Door.hpp
  include/Spike.hpp
  include/Sprite.hpp
  src/App.cpp
  src/Button.cpp
  src/Character.cpp
  src/Door.cpp
  src/Spike.cpp
  src/Sprite.cpp
Labels: enhancement

#33 將Behaviour 改名成Interface 調整cmake順序
  files.cmake
  include/Behaviour.hpp
  include/Button.hpp
  include/Character.hpp
  include/Door.hpp
  include/IBehaviour.hpp
  include/Spike.hpp
  include/Sprite.hpp
Labels: enhancement

#37 新增Level Interface
  files.cmake
  include/App.hpp
  include/Background.hpp
  include/ILevel.hpp
  include/Level.hpp
  include/Level1.hpp
  include/LevelSelect.hpp
  include/Spring.hpp
  src/App.cpp
  src/Background.cpp
  src/Level1.cpp
  src/LevelSelect.cpp
  src/Spring.cpp
Labels: enhancement

#40 fix door animation interval
  src/Door.cpp
Labels: bug

#38 新增角色死亡 復活 通關 記錄點
  include/Character.hpp
  src/Character.cpp
  src/Door.cpp
  src/Level1.cpp
Labels: enhancement

#41 Triggercollider
  files.cmake
  include/TriggerCollider.hpp
  src/TriggerCollider.cpp
Labels: enhancement

#42 fixed trigger collider
  include/TriggerCollider.hpp
Labels: enhancement

#46 解決載入時null src的問題
  include/SoundEffect.hpp
  src/SoundEffect.cpp
Labels: bug

#47 Sfx bug
  Resources/sound/bounce.mp3
  Resources/sound/button.mp3
  Resources/sound/coin.mp3
  Resources/sound/dead.mp3
  Resources/sound/door.mp3
  Resources/sound/outro.mp3
  Resources/sound/revive.mp3
  Resources/sound/saw.mp3
  Resources/sound/stageclear.mp3
  Resources/sound/trap.mp3
  Resources/sound/wall trap.mp3
  include/AudioManager.hpp
  include/Button.hpp
  include/Character.hpp
  include/Coin.hpp
  include/Door.hpp
  include/DoorButton.hpp
  include/LevelSelect.hpp
  include/Spike.hpp
  include/Spring.hpp
  src/Button.cpp
  src/Character.cpp
  src/Coin.cpp
  src/Door.cpp
  src/DoorButton.cpp
  src/Level1.cpp
  src/LevelSelect.cpp
  src/Spike.cpp
  src/Spring.cpp
Labels: bug, enhancement
