Repository 0oWoodenDooro0/LevelDevil, pull requests merged in 2024-05, with the labels that each got.

#84 level3
  Resources/image/level/level2/level2.aseprite
  Resources/image/level/level3/Lbottom.png
  Resources/image/level/level3/Lside.png
  Resources/image/level/level3/Rbottom.png
  Resources/image/level/level3/Rside.png
  Resources/image/level/level3/Rspike.png
  Resources/image/level/level3/background.png
  Resources/image/level/level3/door.png
  Resources/image/level/level3/in_door1.png
  Resources/image/level/level3/in_door2.png
  Resources/image/level/level3/in_door3.png
  Resources/image/level/level3/in_door4.png
  Resources/image/level/level3/in_door5.png
  Resources/image/level/level3/spike.png
  Resources/image/level/level3/top.png
  Resources/image/level/level4/bottom.png
  Resources/image/level/level4/door.png
  Resources/image/level/level4/in_door1.png
  Resources/image/level/level4/in_door2.png
  Resources/image/level/level4/in_door3.png
  Resources/image/level/level4/in_door4.png
  Resources/image/level/level4/in_door5.png
  files.cmake
  include/Level.hpp
  include/Level3.hpp
  include/MovableSpike.hpp
  include/Spike.hpp
  src/App.cpp
  src/Level2.cpp
  src/Level3.cpp
  src/LevelSelect.cpp
  src/MovableSpike.cpp
  src/Spike.cpp
Labels: enhancement

#79 Level4
  Resources/image/level/level4/background.png
  Resources/image/level/level4/bottom.png
  Resources/image/level/level4/coin.png
  Resources/image/level/level4/door.png
  Resources/image/level/level4/in_door1.png
  Resources/image/level/level4/in_door2.png
  Resources/image/level/level4/in_door3.png
  Resources/image/level/level4/in_door4.png
  Resources/image/level/level4/in_door5.png
  Resources/image/level/level4/wall1.png
  Resources/image/level/level4/wall2.png
  Resources/image/level/level4/wall3.png
  Resources/image/level/level4/wall4.png
  Resources/image/level/level4/wall5.png
  files.cmake
  include/Level.hpp
  include/Level4.hpp
  src/App.cpp
  src/Coin.cpp
  src/Level4.cpp
  src/LevelSelect.cpp
Labels: enhancement

#87 level5
  Resources/image/level/level5/background.png
  Resources/image/level/level5/door.png
  Resources/image/level/level5/in_door1.png
  Resources/image/level/level5/in_door2.png
  Resources/image/level/level5/in_door3.png
  Resources/image/level/level5/in_door4.png
  Resources/image/level/level5/in_door5.png
  Resources/image/level/level5/midBottom.png
  Resources/image/level/level5/side.png
  Resources/image/level/level5/sideBottom.png
  Resources/image/level/level5/top.png
  files.cmake
  include/Level.hpp
  include/Level5.hpp
  src/App.cpp
  src/Level5.cpp
  src/LevelSelect.cpp
Labels: enhancement

#93 fix level 4 bug
  include/Character.hpp
  src/Character.cpp
  src/Rigidbody.cpp
Labels: bug

#94 Level7
  Resources/image/level/level7/background.png
  Resources/image/level/level7/bottom.png
  Resources/image/level/level7/door.png
  Resources/image/level/level7/in_door1.png
  Resources/image/level/level7/in_door2.png
  Resources/image/level/level7/in_door3.png
  Resources/image/level/level7/in_door4.png
  Resources/image/level/level7/in_door5.png
  Resources/image/level/level7/side.png
  Resources/image/level/level7/springBase.png
  Resources/image/level/level7/springDown.png
  Resources/image/level/level7/springUp.png
  Resources/image/level/level7/top.png
  files.cmake
  include/AudioManager.hpp
  include/Level.hpp
  include/Level7.hpp
  include/MovableSpring.hpp
  include/Spring.hpp
  src/App.cpp
  src/Character.cpp
  src/CollisionHandler.cpp
  src/Level7.cpp
  src/LevelSelect.cpp
  src/MovableSpring.cpp
  src/Spring.cpp
Labels: bug, enhancement

#97 fix rigidbody
  src/Rigidbody.cpp
Labels: bug

#104 Press R to Reset Level
  include/Door.hpp
  include/InputHandler.hpp
  include/Level1.hpp
  include/Level2.hpp
  include/Level3.hpp
  include/Level4.hpp
  include/Level5.hpp
  include/Level7.hpp
  include/Spring.hpp
  src/Character.cpp
  src/InputHandler.cpp
  src/Level1.cpp
  src/Level2.cpp
  src/Level3.cpp
  src/Level4.cpp
  src/Level5.cpp
  src/Level7.cpp
  src/Spring.cpp
Labels: enhancement

#106 god mode
  include/Character.hpp
  include/InputHandler.hpp
  src/Character.cpp
  src/InputHandler.cpp
  src/Level1.cpp
  src/Level2.cpp
  src/Level3.cpp
  src/Level4.cpp
  src/Level5.cpp
  src/Level7.cpp
Labels: enhancement

#107 fix merge
  include/Door.hpp
  include/Portal.hpp
  src/Level3.cpp
  src/Portal.cpp
Labels: bug

#108 Level8
  Resources/image/level/level8/Lbottom.png
  Resources/image/level/level8/Lside.png
  Resources/image/level/level8/Ltop.png
  Resources/image/level/level8/Rbottom.png
  Resources/image/level/level8/Rside.png
  Resources/image/level/level8/background.png
  Resources/image/level/level8/door.png
  Resources/image/level/level8/in_door1.png
  Resources/image/level/level8/in_door2.png
  Resources/image/level/level8/in_door3.png
  Resources/image/level/level8/in_door4.png
  Resources/image/level/level8/in_door5.png
  Resources/image/level/level8/platform.png
  Resources/image/level/level8/portal1.png
  Resources/image/level/level8/portal2.png
  Resources/image/level/level8/top.png
  files.cmake
  include/Door.hpp
  include/Level.hpp
  include/Level8.hpp
  include/Portal.hpp
  src/App.cpp
  src/Level8.cpp
  src/LevelSelect.cpp
  src/Portal.cpp
Labels: enhancement

#109 fix sonarcloud
  include/SoundEffect.hpp
  src/SoundEffect.cpp
Labels: refactor

#110 fix 會穿spring
  include/Character.hpp
  include/Level1.hpp
  include/Level2.hpp
  include/Level3.hpp
  include/Level4.hpp
  include/Level5.hpp
  include/Level7.hpp
  include/Rigidbody.hpp
  src/Character.cpp
  src/Level7.cpp
  src/Rigidbody.cpp
Labels: bug

#113 Saw
  include/Saw.hpp
  src/Saw.cpp
Labels: enhancement
